SELECT DECODE (VCD.REVENUECENTERID, 10650,'BAR',
                                    10651,'TIENDA',
                                    10652,'SPA',
                                    11100,'HSK',
                                    10351,'RESTAURANTE',
                                    11100,'COC. PERSONAL') RVC,
      VCH.CHECKNUM NRO_CHECK,
      VCH.NUMGUESTS COMENSALES,
      VCD.BUSINESSDATE FECHA,
      VCD.TRANSDATETIME,
      VCD.TRANSEMPNAME EMPLEADO,
      VCD.LINECOUNT CONT_LINEA,
      VCD.LINETOTAL MONTO_LINEA,
      VCD.ITEMNAME NOMBRE_ITEM,
      VCD.ITEMNUMBER NRO_ITEM, 
      VCD.TENDERNAME FORMA_PAGO,
      TN.TENDERNAME,
      VCH.SERVICECHARGETOTAL PROPINAS,
      VCD.FAMILYGROUPNAME GRUPO_FAMILIA,
      VCD.MAJORGROUPNAME GRUPO_MAJOR,
      VCD.VOIDFLAGTF ANULACION,
      VCD.REASONNAME ANULACION_RAZON
  FROM VMM_CHECK_DETAILS VCD, 
       VMM_CHECK_HEADERS VCH,
      (SELECT  TENDERNAME,
               BUSINESSDATE,
               REVENUECENTERID,
               GUESTCHECKID
         FROM VMM_CHECK_DETAILS
        WHERE TENDERNAME IS NOT NULL) TN
  WHERE VCD.BUSINESSDATE >= '05-SEP-19'
  AND VCD.GUESTCHECKID = VCH.GUESTCHECKID
  AND VCD.LINETOTAL <> 0
  AND VCD.REVENUECENTERID <> '13452'
  AND VCD.BUSINESSDATE = TN.BUSINESSDATE
  AND VCD.GUESTCHECKID = TN.GUESTCHECKID


